function iso(value){return value instanceof Date?value.toISOString():String(value||'')}
function roomFromRow(row){if(!row)return null;return{id:row.id,hostId:row.host_id,title:row.title,status:row.status,viewerCount:0,createdAt:iso(row.created_at),endedAt:row.ended_at?iso(row.ended_at):null}}
function messageFromRow(row){if(!row)return null;return{id:row.id,liveId:row.live_id,userId:row.user_id,username:row.username||'',text:row.body,createdAt:iso(row.created_at)}}

export class PostgresLiveRepository {
  constructor(pool=null){this.pool=pool}
  get enabled(){return !!this.pool}

  async createRoom(room){const result=await this.pool.query('INSERT INTO live_rooms(id,host_id,title,status,created_at,ended_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[room.id,room.hostId,room.title,room.status,room.createdAt,room.endedAt]);return roomFromRow(result.rows[0])}
  async findLiveRoom(id){const result=await this.pool.query("SELECT * FROM live_rooms WHERE id=$1 AND status='live' LIMIT 1",[id]);return roomFromRow(result.rows[0])}
  async listActiveRooms(limit=100){const result=await this.pool.query("SELECT * FROM live_rooms WHERE status='live' ORDER BY created_at DESC,id DESC LIMIT $1",[Math.max(1,Math.min(200,Number(limit)||100))]);return result.rows.map(roomFromRow)}
  async endRoom(id,hostId,endedAt){const result=await this.pool.query("UPDATE live_rooms SET status='ended',ended_at=$3 WHERE id=$1 AND host_id=$2 AND status='live' RETURNING *",[id,hostId,endedAt]);return roomFromRow(result.rows[0])}
  async listMessages(liveId,limit=200){const result=await this.pool.query('SELECT m.*,u.username FROM live_messages m JOIN users u ON u.id=m.user_id WHERE m.live_id=$1 ORDER BY m.created_at DESC,m.id DESC LIMIT $2',[liveId,Math.max(1,Math.min(200,Number(limit)||200))]);return result.rows.reverse().map(messageFromRow)}
  async createMessage(message){const result=await this.pool.query('INSERT INTO live_messages(id,live_id,user_id,body,created_at) VALUES($1,$2,$3,$4,$5) RETURNING *',[message.id,message.liveId,message.userId,message.text,message.createdAt]);return{...messageFromRow(result.rows[0]),username:message.username||''}}
  async engagement(liveId){await this.pool.query('INSERT INTO live_engagement(live_id) VALUES($1) ON CONFLICT(live_id) DO NOTHING',[liveId]);const r=await this.pool.query('SELECT likes,resonance FROM live_engagement WHERE live_id=$1',[liveId]);return{likes:Number(r.rows[0]?.likes||0),resonance:Number(r.rows[0]?.resonance||0)}}
  async addLike(liveId,amount=1){const n=Math.max(1,Math.min(20,Number(amount)||1));const r=await this.pool.query('INSERT INTO live_engagement(live_id,likes,resonance) VALUES($1,$2,$2) ON CONFLICT(live_id) DO UPDATE SET likes=live_engagement.likes+$2,resonance=live_engagement.resonance+$2,updated_at=now() RETURNING likes,resonance',[liveId,n]);await this.pool.query("UPDATE live_battles SET host_score=host_score+CASE WHEN host_live_id=$1 THEN $2 ELSE 0 END,opponent_score=opponent_score+CASE WHEN opponent_live_id=$1 THEN $2 ELSE 0 END WHERE status='live' AND ends_at>now() AND (host_live_id=$1 OR opponent_live_id=$1)",[liveId,n]);return{likes:Number(r.rows[0].likes),resonance:Number(r.rows[0].resonance)}}
  async activeBattle(liveId){await this.pool.query("UPDATE live_battles SET status='ended',ended_at=now() WHERE status='live' AND ends_at<=now() AND (host_live_id=$1 OR opponent_live_id=$1)",[liveId]);const r=await this.pool.query("SELECT * FROM live_battles WHERE status='live' AND (host_live_id=$1 OR opponent_live_id=$1) ORDER BY started_at DESC LIMIT 1",[liveId]);const x=r.rows[0];return x?{id:x.id,hostLiveId:x.host_live_id,opponentLiveId:x.opponent_live_id,status:x.status,hostScore:Number(x.host_score),opponentScore:Number(x.opponent_score),startedAt:iso(x.started_at),endsAt:iso(x.ends_at)}:null}
  async createBattle({id,hostLiveId,opponentLiveId,startedAt,endsAt}){const client=await this.pool.connect();try{await client.query('BEGIN');await client.query('SELECT id FROM live_rooms WHERE id IN ($1,$2) ORDER BY id FOR UPDATE',[hostLiveId,opponentLiveId]);const active=await client.query("SELECT id FROM live_battles WHERE status='live' AND (host_live_id IN ($1,$2) OR opponent_live_id IN ($1,$2)) LIMIT 1",[hostLiveId,opponentLiveId]);if(active.rowCount){const error=new Error('RESONANCE_ALREADY_ACTIVE');error.code='RESONANCE_ALREADY_ACTIVE';throw error}const r=await client.query("INSERT INTO live_battles(id,host_live_id,opponent_live_id,status,started_at,ends_at) VALUES($1,$2,$3,'live',$4,$5) RETURNING *",[id,hostLiveId,opponentLiveId,startedAt,endsAt]);await client.query('COMMIT');const x=r.rows[0];return{id:x.id,hostLiveId:x.host_live_id,opponentLiveId:x.opponent_live_id,status:x.status,hostScore:Number(x.host_score),opponentScore:Number(x.opponent_score),startedAt:iso(x.started_at),endsAt:iso(x.ends_at)}}catch(error){try{await client.query('ROLLBACK')}catch{}throw error}finally{client.release()}}
}
